services:
  personalwebsite-frontend:
    restart: unless-stopped
    container_name: personalwebsite-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    networks:
      - personalwebsite-network

networks:
  personalwebsite-network:
    driver: bridge
